name: zedsecure
description: "A professional VPN application with iOS-style UI design"
publish_to: 'none'

version: 1.5.0+6

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  flutter_v2ray_client:
    path: local_packages/flutter_v2ray_client
  
  http: ^1.5.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  connectivity_plus: ^7.0.0
  path_provider: ^2.1.5
  mobile_scanner: ^7.1.2
  qr_flutter: ^4.1.0
  permission_handler: ^12.0.1
  country_flags: ^3.0.0
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

dependency_overrides:
  intl: ^0.20.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/flags/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "ZedSecureicon.png"
  adaptive_icon_background: "#00D9E1"
  adaptive_icon_foreground: "ZedSecureicon.png"
